language: node_js
node_js:
  - 6
  - 8
  - node

install:
  - npm install
  - npm install codecov

after_success:
  - $(npm bin)/nyc report --reporter=lcovonly
  - $(npm bin)/codecov
  - ./docs/publish.sh
